name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--lint'
          task: 'run'
          stagein: ''
        
    
