name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--lint'

  test:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0

      - name: test workflow
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: Snakefile
          args: "--use-conda -j 2"

      - name: print environment hash
        id: print_hash
        run: |
          pwd
          ls
          ls /
          /home/runner/work/minimal-smk/minimal-smk/condaenv.py
        shell: bash

      - name: get environment hash
        id: get_env_hash
        run: |
          echo "::set-output hash=/home/runner/work/minimal-smk/minimal-smk/condaenv.py 2> /dev/null"
        shell: bash

      - name: cache-conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: .snakemake/conda
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ steps.get_env_hash.outputs.hash }}
