name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--lint'
          task: 'run'
          stagein: ''
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: Install workflow environments         # FIXME: target for cache
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: Snakefile
          args: "--use-conda -j 2 --conda-create-envs-only"
      - name: test workflow
        uses: snakemake/snakemake-github-action-@v1.23.0
        with:
          directory: .
          snakefile: Snakefile
          args: "--use-conda -j 2"
